[env]
VIOLET_PATH = { script = ["pwd"] }
VIOLET_RLS_BIN_PATH = "${VIOLET_PATH}/target/riscv64imac-unknown-none-elf/release"
VIOLET_DBG_BIN_PATH = "${VIOLET_PATH}/target/riscv64imac-unknown-none-elf/debug"
VIOLET_BIN_PATH = "${VIOLET_DBG_BIN_PATH}"
OUTPUT_FILE_NAME = "violet.bin"
APP_NAME = "sample"
#CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true # workspaceの各クレートに対して、本makefileを提供する

[config]
default_to_workspace = false

#######################
# Violet自体のビルド
#######################

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.rebuild]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build_elf]
command = "cargo"
args = ["build"]

[tasks.objcopy]
dependencies = ["build_elf"]
script = "riscv64-unknown-elf-objcopy -O binary ${VIOLET_BIN_PATH}/${APP_NAME} ${VIOLET_BIN_PATH}/${OUTPUT_FILE_NAME}"

[tasks.build]
command = "echo"
args = ["======== build finished ========"]
dependencies = ["objcopy"]

#######################
# 開発環境構築
#######################
[tasks.build_another_project]
script = "tools/build_another_project.sh"

[tasks.build_opensbi]
script = "tools/build_another_project.sh -o"

[tasks.build_linux]
script = "tools/build_another_project.sh -l"

[tasks.build_busybox]
script = "tools/build_another_project.sh -b"

[tasks.target_add]
script = "rustup target add riscv64imac-unknown-none-elf"

[tasks.build_projects]
dependencies = [
    "build_opensbi",
    "build_linux",
    "build_busybox",
]

[tasks.all]
run_task = [
    { name = ["target_add", "build", "build_projects"] },
]

#######################
# Violetの実行
#######################

[tasks.run]
script = "tools/run_linux.sh"

[tasks.debug]
script = "tools/run_linux.sh -d"

[tasks.monitor]
script = "tools/debug.sh -m"

#######################
# テストなど、そのほか
#######################
[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]
