[profile.dev]
opt-level = 0

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -cpu rv64 -M virt -nographic -m 2G -smp 1 -bios /opt/riscv/opensbi/build/platform/generic/firmware/fw_jump.elf -kernel "

[build]
target = "riscv64imac-unknown-none-elf"
rustflags = [
    "-C", "link-arg=-Tqemu_virt.ld", 
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true