[package]
name = "freertos_sample"
version = "0.1.0"
authors = ["ryamamoto"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
violet = { path = "../../violet" }
vmmode = { path = "../../plugin/vmmode" }
