[profile.dev]
opt-level = 0

[target.riscv32i-unknown-none-elf]
runner = "qemu-system-riscv32 -nographic -machine sifive_u -m 512M -bios "
rustflags = [
    "-C", "link-arg=-Tconfig/ld/sifive.ld",
]

[target.riscv32imac-unknown-none-elf]
runner = "qemu-system-riscv32 -nographic -machine sifive_u -m 512M -gdb tcp::12345 -S -bios "
rustflags = [
    "-C", "link-arg=-Tconfig/ld/sifive.ld",
]

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -machine sifive_u -m 512M -bios "

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -machine sifive_u -m 512M -bios "
rustflags = [
    "-C", "link-arg=-Tconfig/ld/rocket_pk.ld",
]

[target.x86_64-unknown-uefi]
runner = "qemu-system-x86_64 -monitor stdio -drive if=pflash,format=raw,readonly,file=tools/OVMFs/OVMF_CODE.fd -drive if=pflash,format=raw,file=tools/OVMFs/OVMF_VARS.fd -device nec-usb-xhci,id=xhci -device usb-mouse -device usb-kbd -drive if=ide,index=0,media=disk,format=raw,file="
rustflags = [
    #"-C", "link-arg=-Tconfig/ld/x86_64.ld",
]

[build]
#target = "riscv32i-unknown-none-elf"
#target = "riscv32imac-unknown-none-elf"
#target = "riscv64gc-unknown-none-elf"
#target = "x86_64-unknown-uefi"
target = "riscv64imac-unknown-none-elf"
rustflags = [
    #"-C", "link-arg=-Tconfig/ld/sifive.ld", 
    "-C", "link-arg=-Tconfig/ld/qemu_virt.ld", 
    "-C", "code-model=medium",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true