[profile.dev]
opt-level = 0

[target.riscv32imac-unknown-none-elf]
runner = "qemu-system-riscv32 -nographic -machine sifive_u -m 512M -gdb tcp::12345 -S -bios "
rustflags = [
    "-C", "link-arg=-Tconfig/ld/sifive.ld",
]

[target.riscv64imac-unknown-none-elf]
runner = "tools/script/command.sh -r "

[build]
#target = "riscv32imac-unknown-none-elf"
target = "riscv64imac-unknown-none-elf"
rustflags = [
    "-C", "link-arg=-Tconfig/ld/qemu_virt.ld", 
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
unstable-options = true