[package]
name = "violet"
version = "0.4.0"
authors = ["nekomaru0510 <yama05rymy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html