name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag violet-test

    - name: Run the Docker image (violet-test)
      run: docker run -v $PWD:/workspaces/Violet violet-test /workspaces/Violet/violet/test.sh

    - name: Run the Docker image (linux-test)
      run: docker run -v $PWD:/workspaces/Violet violet-test /workspaces/Violet/proj/qemu_linux/tools/test.sh
    
    - name: Run the Docker image (freertos-test)
      run: docker run -v $PWD:/workspaces/Violet violet-test /workspaces/Violet/proj/qemu_freertos/tools/test.sh
